name:                haskell-programming
version:             0.1.0.0
github:              "martinrist/haskell-programming"
license:             BSD3
author:              "Martin Rist"
maintainer:          "mlr-github@martinrist.com"
copyright:           "2019 Martin Rist"

library:
  source-dirs:
    - src
    - test
  ghc-options:
    - -Wall
    - -Werror
  dependencies:
    - base
    - time
    - hspec
    - containers
    - QuickCheck
    - hspec-checkers
    - optparse-applicative
    - checkers
    - bytestring
    - wreq
    - random
    - transformers
    - trifecta
    - parsers
    - text
    - raw-strings-qq
    - attoparsec
    - scotty
    - criterion
    - bytestring
    - network
    - sqlite-simple
    - safe
    - wai
    - warp
    - aeson
    - servant
    - servant-server
    - servant-client
    - servant-docs

executables:

  hangman:
    main:           Main.hs
    source-dirs:    app/hangman
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - base
      - haskell-programming

  encrypt:
    main:           Main.hs
    source-dirs:    app/encrypt
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - base
      - haskell-programming
      - optparse-applicative

  morse:
    main:           Main.hs
    source-dirs:    app/morse
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - base
      - haskell-programming

tests:
  haskell-programming-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
    dependencies:
      - base
      - hspec
      - hspec-discover
      - haskell-programming
      - QuickCheck
      - checkers
      - hspec-checkers
